import os

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
FACEBOOK_TOKEN = os.getenv("FACEBOOK_TOKEN")
INSTAGRAM_TOKEN = os.getenv("INSTAGRAM_TOKEN")
AFFILIATE_TAG = "todoenunoofic-20"
AMAZON_DOMAIN = "https://www.amazon.com"
POST_INTERVAL = 3600
PRODUCT_LIMIT = 5
PAGE_ID = os.getenv("PAGE_ID")
INSTAGRAM_ACCOUNT_ID = os.getenv("INSTAGRAM_ACCOUNT_ID")
RAPIDAPI_KEY = os.getenv("RAPIDAPI_KEY")
